reportError: don't use modal dialogs, because this could lead to a thread dead lock invoke ErrorlogPane.appendLog and other gui stuff within SwingUtilities.invokeLater Related to #52